# Basic
title: JieWei
subtitle: å‡¡æ˜¯äºº æ€»æœ‰å–èˆ.

description: Welcome to my blog,I'm Zhang Jiewei,ä¸€åiOSå¼€å‘è€….è¿½æ±‚ç‰©è´¨çš„åŒæ—¶,ä¹Ÿæƒ³ç€èƒ½è¯»å¾ˆå¤šä¹¦,èµ°å¾ˆå¤šè·¯,è¿‡ç®€å•çš„ç”Ÿæ´»,æ¢¦é‡Œåªæœ‰è¯—äººå’Œè¿œæ–¹ğŸƒğŸƒ.

# creator: <a href="http://blog.zhangjiewei.com">@JieWei</a>

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Product, description: My Product, url: 'http://b.mashort.cn/h.m6KUG?cv=AADXnjmh&sm=9f3c25'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: Anderson-Lii
    github: JieWei-Zhang
    mail: 836654084@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
